apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: secret
  description: 'Share Secrets securily '
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: group:cds-snc/internal-sre
