name: "A11y tracker"

on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  run-a11y-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Run a11y tracker
        run: |
          curl -s https://api.a11y.cdssandbox.xyz/v1/reports\?recent\=true > /dev/null
          sleep 60
          echo '{"product": "cds-snc/secret", "revision": "${{github.sha}}", "urls":["https://secret.cdssandbox.xyz"], "spider": 1}' | http POST https://api.a11y.cdssandbox.xyz/v1 X-API-KEY:${{ secrets.A11Y_TRACKER_KEY }}
