name: "CD Terraform"

on:
  push:
    branches:
      - main
    paths:
      - "aws/**"
      - "secret/**"
      - "terragrunt/**"
      - ".github/workflows/**"

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 0.13.5
  TERRAGRUNT_VERSION: 0.26.0
  TF_VAR_git_sha: ${{ github.sha }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Apply aws/acm
        working-directory: terragrunt/acm
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Install python if needed
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.8'

      - run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Build lambda if needed
        run: |
          python -m pip install --upgrade pip
          make install
          make package

      - name: Apply aws/lambda
        working-directory: terragrunt/lambda
        run: terragrunt apply --terragrunt-non-interactive -auto-approve