name: "CD Terraform"

on:
  push:
    branches:
      - main
    paths:
      - "aws/**"
      - "secret/**"
      - "terragrunt/**"
      - ".github/workflows/merge_to_main.yaml"

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 0.13.5
  TERRAGRUNT_VERSION: 0.26.0
  TF_VAR_git_sha: ${{ github.sha }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Setup Terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: arn:aws:iam::637287734259:role/secret-apply
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply aws/acm
        working-directory: terragrunt/acm
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Install python if needed
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: '3.8'

      - run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Build lambda if needed
        run: |
          python -m pip install --upgrade pip
          make install
          make package

      - name: Apply aws/lambda
        working-directory: terragrunt/lambda
        run: terragrunt apply --terragrunt-non-interactive -auto-approve