name: "CI Lambda"

on:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  go-tests:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    container: golang:1.26.6@sha256:0d1d3a794be25f809dd2cb3160d8c73276c4056a9f8242a138e908ddeee7b6b6

    services:
      dynamodb-local:
        image: "amazon/dynamodb-local@sha256:d89f8fcc6b1a39cb35976c248ed42a28c66ae00dc043099210f5571e42648ab4"
        ports:
          - 8000:8000

      local-kms:
        image: nsmithuk/local-kms@sha256:e070866476b20973a9e23a9b636204b7a222e4169a6e03198d27b80d47ed28e3
        ports:
          - "8080:8080"
        volumes:
          - "${{ github.workspace }}/.devcontainer/docker/kms/data:/data/"
          - "${{ github.workspace }}/.devcontainer/docker/kms/init:/init/"
        env:
          KMS_REGION: "ca-central-1"

    steps:
      - name: Checkout
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Restart local-kms
        # Restart local-kms after volumes have been checked out
        # https://github.com/orgs/community/discussions/42127
        uses: docker://docker@sha256:bfec1f5159c63a81ca6fdedbd81404d2c0e16378ed0feec3bb3fbf3998847659
        with:
          args: docker restart "${{ job.services.local-kms.id }}"

      - name: Install dependencies
        run: go get .

      - name: Test
        run: make test
        env:
          AWS_ACCESS_KEY_ID: "AWSACCESSKEYID"
          AWS_SECRET_ACCESS_KEY: "AWSSECRETACCESSKEY"
